package com.company.bashar;

import com.intellij.ui.AnimatedIcon;

import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String args[]) throws NoSuchAlgorithmException
    {
        String s = "My name is";

        String hashValue = MdFiveHashFunction.getMd5(s);

        System.out.println("Your HashCode length: " + hashValue.length());
        System.out.println("Your HashCode Generated by MD5 is: " + hashValue);

        String xValue = hashValue.substring(0, 16);
        String yValue = hashValue.substring(16);

        //String hashtext = xValue.toString(10);

        System.out.println(xValue);
        System.out.println(yValue);

        BigInteger xCoordinator = new BigInteger(xValue, 16);
        BigInteger yCoordinator = new BigInteger(yValue, 16);

        BigInteger bi = xCoordinator.add(yCoordinator);


        System.out.println(xCoordinator);
        System.out.println(yCoordinator);


        List list = new ArrayList();

        list.add(xCoordinator);
        list.add(yCoordinator);


        System.out.println(CenterOfMass.calculate(list));
    }
}


