package com.company.bashar;

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String args[]) throws NoSuchAlgorithmException
    {
        String s = "My name is Jahid";

        String hashValue = MdFiveHashFunction.getMd5(s);

        System.out.println("Your HashCode length: " + hashValue.length());
        System.out.println("Your HashCode Generated by MD5 is: " + hashValue);

        String xValue = hashValue.substring(0, 16);
        String yValue = hashValue.substring(16);

        System.out.println(xValue);
        System.out.println(yValue);

        //Long xCoordinator = Long.valueOf(Integer.parseInt(xValue, 16));

        //System.out.println(xCoordinator);


        List list = new ArrayList();

        list.add(2);
        list.add(4);
        list.add(5);
        list.add(1);

        System.out.println(CenterOfMass.calculate(list));
    }
}


